---
language: ruby

sudo: required

rvm:
  - 2.2.5

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

install: gem install rubocop

script:
  - "for file in $(find . -type f -name *.sh); do docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/$file; done"
  - rubocop -SD Vagrantfile

matrix:
  fast_finish: true
