---
language: ruby

sudo: false

rvm:
  - 2.2.5

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

install: gem install rubocop

script:
  - bash -c 'shopt -s globstar; shellcheck **/*.sh'
  - rubocop -SD Vagrantfile

matrix:
  fast_finish: true
