---
language: ruby

sudo: required

rvm:
  - 2.2.5

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

install: gem install rubocop

script:
  - "docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/bing-wallpaper.sh"
  - rubocop -SD Vagrantfile

matrix:
  fast_finish: true
